{% set name = "django-bootstrap-datepicker-plus" %}
{% set version = "5.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_bootstrap_datepicker_plus-{{ version }}.tar.gz
  sha256: fac3f7aeacd3fa63a9829077983ff728aea145f5a4f493c5dfbf870cb36c53ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - django >=2,<5
    - pydantic *
    - typing-extensions *

about:
  home: https://github.com/monim67/django-bootstrap-datepicker-plus
  summary: Bootstrap3/Bootstrap4/Bootstrap5 DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gb119
